version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123

  backend:
    build: .
    container_name: nest-backend
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - mongo
