name: Deploy Backend

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/nestService

            git fetch
            git checkout build
            git pull origin build

            # 🧹 stop containers
            docker compose down

            # 🔨 rebuild + run
            docker compose up -d --build

            # 🧽 clean unused images (optional แต่แนะนำ)
            docker image prune -f
